from app.agents.base.base_agent import BaseAgent
from app.artifacts.prd import PRDArtifact
from app.state.workflow_state import WorkflowState


class ProductManager(BaseAgent):

    def execute(
        self,
        state: WorkflowState,
    ) -> WorkflowState:

        state["current_agent"] = "Product Manager"

        state["completed_agents"].append(
            "Product Manager"
        )

        state["artifacts"]["product_requirements"] = (
            PRDArtifact(
                title=state["user_request"],
                summary="Initial Product Requirements Document generated by Product Manager."
            ).to_dict()
        )

        state["messages"].append(
            "Product Requirements Document created."
        )

        return state